[package]
authors = ['zCloak Network']
build = 'build.rs'
description = 'zCloak network verifier node'
edition = '2018'
homepage = 'https://zcloak.network'
license = 'Unlicense'
name = 'zcloak-node'
repository = 'https://github.com/substrate-developer-hub/substrate-node-template/'
version = '2.0.1'

[[bin]]
name = 'zcloak-node'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = '2.0.1'

[dependencies]
jsonrpc-core = '15.0.0'
structopt = '0.3.8'

# local dependencies
node-template-runtime = { path = '../runtime' }

# Substrate dependencies
frame-benchmarking = {git = "https://github.com/Starks-Network/substrate"}
frame-benchmarking-cli = { git = "https://github.com/Starks-Network/substrate"}
pallet-transaction-payment-rpc = { git = "https://github.com/Starks-Network/substrate"}
sc-basic-authorship = { git = "https://github.com/Starks-Network/substrate"}
sc-cli = { features = ['wasmtime'],  git = "https://github.com/Starks-Network/substrate" }
sc-client-api = {git = "https://github.com/Starks-Network/substrate" }
sc-consensus = { git = "https://github.com/Starks-Network/substrate" }
sc-consensus-aura = { git = "https://github.com/Starks-Network/substrate" }
sc-executor = { features = ['wasmtime'],  git = "https://github.com/Starks-Network/substrate" }
sc-finality-grandpa = { git = "https://github.com/Starks-Network/substrate" }
sc-rpc = {git = "https://github.com/Starks-Network/substrate" }
sc-rpc-api = { git = "https://github.com/Starks-Network/substrate" }
sc-service = { features = ['wasmtime'],git = "https://github.com/Starks-Network/substrate" }
sc-transaction-pool = {git = "https://github.com/Starks-Network/substrate" }
sp-api = {git = "https://github.com/Starks-Network/substrate" }
sp-block-builder = {git = "https://github.com/Starks-Network/substrate" }
sp-blockchain = {git = "https://github.com/Starks-Network/substrate" }
sp-consensus = { git = "https://github.com/Starks-Network/substrate" }
sp-consensus-aura = { git = "https://github.com/Starks-Network/substrate" }
sp-core = {git = "https://github.com/Starks-Network/substrate" }
sp-finality-grandpa = { git = "https://github.com/Starks-Network/substrate" }
sp-inherents = { git = "https://github.com/Starks-Network/substrate" }
sp-runtime = { git = "https://github.com/Starks-Network/substrate" }
sp-transaction-pool = { git = "https://github.com/Starks-Network/substrate" }
substrate-frame-rpc-system = { git = "https://github.com/Starks-Network/substrate" }

[features]
default = []
runtime-benchmarks = ['node-template-runtime/runtime-benchmarks']
